[rospy.client][INFO] 2017-07-07 09:49:58,517: init_node, name[/move_sandbox_items], pid[3476]
[xmlrpc][INFO] 2017-07-07 09:49:58,517: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2017-07-07 09:49:58,518: Started XML-RPC server [http://sandtray-hrilab:44359/]
[rospy.init][INFO] 2017-07-07 09:49:58,518: ROS Slave URI: [http://sandtray-hrilab:44359/]
[rospy.impl.masterslave][INFO] 2017-07-07 09:49:58,518: _ready: http://sandtray-hrilab:44359/
[rospy.registration][INFO] 2017-07-07 09:49:58,519: Registering with master node http://localhost:11311
[xmlrpc][INFO] 2017-07-07 09:49:58,519: xml rpc node: starting XML-RPC server
[rospy.init][INFO] 2017-07-07 09:49:58,618: registered with master
[rospy.rosout][INFO] 2017-07-07 09:49:58,618: initializing /rosout core topic
[rospy.rosout][INFO] 2017-07-07 09:49:58,620: connected to core topic /rosout
[rospy.simtime][INFO] 2017-07-07 09:49:58,621: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rospy.internal][INFO] 2017-07-07 09:49:58,636: topic[/tf] adding connection to [http://sandtray-hrilab:41209/], count 0
[rospy.internal][INFO] 2017-07-07 09:49:58,638: topic[/tf] adding connection to [http://sandtray-hrilab:39102/], count 1
[rospy.internal][INFO] 2017-07-07 09:49:58,639: topic[/tf] adding connection to [http://sandtray-hrilab:35092/], count 1
[rospy.internal][INFO] 2017-07-07 09:49:58,639: topic[/tf] adding connection to [http://sandtray-hrilab:40388/], count 1
[rospy.internal][INFO] 2017-07-07 09:49:58,640: topic[/tf] adding connection to [http://sandtray-hrilab:37713/], count 2
[rospy.internal][INFO] 2017-07-07 09:49:58,781: topic[/poses] adding connection to [/sandtray], count 0
[rospy.internal][INFO] 2017-07-07 09:49:58,880: topic[/rosout] adding connection to [/rosout], count 0
[rospy.internal][WARNING] 2017-07-07 09:52:04,245: Unknown error initiating TCP/IP socket to sandtray-hrilab:42425 (http://sandtray-hrilab:39102/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 555, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][INFO] 2017-07-07 09:52:04,245: topic[/tf] removing connection to http://sandtray-hrilab:39102/
[rospy.internal][INFO] 2017-07-07 09:54:35,772: topic[/tf] adding connection to [http://sandtray-hrilab:44278/], count 4
[rospy.internal][INFO] 2017-07-07 09:54:37,089: topic[/tf] adding connection to [http://sandtray-hrilab:38979/], count 5
[rospy.internal][WARNING] 2017-07-07 10:03:45,192: Unknown error initiating TCP/IP socket to sandtray-hrilab:45003 (http://sandtray-hrilab:44278/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rosgraph/network.py", line 362, in read_ros_handshake_header
    d = sock.recv(buff_size)
error: [Errno 104] Connection reset by peer

[rospy.internal][INFO] 2017-07-07 10:03:45,192: topic[/tf] removing connection to http://sandtray-hrilab:44278/
[rospy.internal][WARNING] 2017-07-07 10:03:45,195: Unknown error initiating TCP/IP socket to sandtray-hrilab:58046 (http://sandtray-hrilab:38979/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 555, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][INFO] 2017-07-07 10:03:45,195: topic[/tf] removing connection to http://sandtray-hrilab:38979/
[rospy.internal][INFO] 2017-07-07 10:03:55,181: topic[/tf] adding connection to [http://sandtray-hrilab:41744/], count 4
[rospy.internal][INFO] 2017-07-07 10:03:56,146: topic[/tf] adding connection to [http://sandtray-hrilab:33146/], count 5
[rospy.internal][WARNING] 2017-07-07 10:15:27,100: Unknown error initiating TCP/IP socket to sandtray-hrilab:45856 (http://sandtray-hrilab:33146/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 555, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][INFO] 2017-07-07 10:15:27,100: topic[/tf] removing connection to http://sandtray-hrilab:33146/
[rospy.internal][WARNING] 2017-07-07 10:15:27,100: Unknown error initiating TCP/IP socket to sandtray-hrilab:48118 (http://sandtray-hrilab:41744/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rosgraph/network.py", line 362, in read_ros_handshake_header
    d = sock.recv(buff_size)
error: [Errno 104] Connection reset by peer

[rospy.internal][INFO] 2017-07-07 10:15:27,101: topic[/tf] removing connection to http://sandtray-hrilab:41744/
[rospy.core][INFO] 2017-07-07 10:20:19,137: signal_shutdown [signal-15]
[rospy.internal][WARNING] 2017-07-07 10:20:19,138: Unknown error initiating TCP/IP socket to sandtray-hrilab:59990 (http://sandtray-hrilab:35092/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 555, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][INFO] 2017-07-07 10:20:19,139: topic[/tf] removing connection to http://sandtray-hrilab:35092/
[rospy.internal][INFO] 2017-07-07 10:20:19,146: topic[/poses] removing connection to /sandtray
[rospy.internal][INFO] 2017-07-07 10:20:19,147: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2017-07-07 10:20:19,147: topic[/tf] removing connection to http://sandtray-hrilab:41209/
[rospy.internal][INFO] 2017-07-07 10:20:19,147: topic[/tf] removing connection to http://sandtray-hrilab:40388/
[rospy.internal][INFO] 2017-07-07 10:20:19,147: topic[/tf] removing connection to http://sandtray-hrilab:37713/
[rospy.impl.masterslave][INFO] 2017-07-07 10:20:19,147: signal-15
[rospy.core][INFO] 2017-07-07 10:20:19,332: signal_shutdown [signal-2]
[rospy.core][INFO] 2017-07-07 10:20:19,332: signal_shutdown [atexit]
