[rospy.client][INFO] 2017-06-23 10:49:19,426: init_node, name[/move_sandbox_items], pid[13264]
[xmlrpc][INFO] 2017-06-23 10:49:19,426: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2017-06-23 10:49:19,426: Started XML-RPC server [http://sandtray-hrilab:36098/]
[rospy.init][INFO] 2017-06-23 10:49:19,427: ROS Slave URI: [http://sandtray-hrilab:36098/]
[rospy.impl.masterslave][INFO] 2017-06-23 10:49:19,427: _ready: http://sandtray-hrilab:36098/
[xmlrpc][INFO] 2017-06-23 10:49:19,427: xml rpc node: starting XML-RPC server
[rospy.registration][INFO] 2017-06-23 10:49:19,427: Registering with master node http://localhost:11311
[rospy.init][INFO] 2017-06-23 10:49:19,527: registered with master
[rospy.rosout][INFO] 2017-06-23 10:49:19,527: initializing /rosout core topic
[rospy.rosout][INFO] 2017-06-23 10:49:19,529: connected to core topic /rosout
[rospy.simtime][INFO] 2017-06-23 10:49:19,530: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rospy.internal][INFO] 2017-06-23 10:49:19,544: topic[/tf] adding connection to [http://sandtray-hrilab:43119/], count 0
[rospy.internal][INFO] 2017-06-23 10:49:19,546: topic[/tf] adding connection to [http://sandtray-hrilab:34885/], count 1
[rospy.internal][INFO] 2017-06-23 10:49:19,547: topic[/tf] adding connection to [http://sandtray-hrilab:44591/], count 2
[rospy.internal][INFO] 2017-06-23 10:49:19,549: topic[/tf] adding connection to [http://sandtray-hrilab:33170/], count 3
[rospy.internal][INFO] 2017-06-23 10:49:19,550: topic[/tf] adding connection to [http://sandtray-hrilab:43520/], count 3
[rospy.internal][INFO] 2017-06-23 10:49:19,680: topic[/poses] adding connection to [/sandtray], count 0
[rospy.internal][INFO] 2017-06-23 10:49:19,781: topic[/rosout] adding connection to [/rosout], count 0
[rospy.internal][WARNING] 2017-06-23 10:49:52,875: Unknown error initiating TCP/IP socket to sandtray-hrilab:48856 (http://sandtray-hrilab:34885/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 555, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][INFO] 2017-06-23 10:49:52,875: topic[/tf] removing connection to http://sandtray-hrilab:34885/
[rospy.internal][INFO] 2017-06-23 10:49:53,882: topic[/tf] adding connection to [http://sandtray-hrilab:43209/], count 4
[rospy.internal][INFO] 2017-06-23 10:49:54,798: topic[/tf] adding connection to [http://sandtray-hrilab:42464/], count 5
[rospy.internal][WARNING] 2017-06-23 11:30:19,369: Unknown error initiating TCP/IP socket to sandtray-hrilab:49258 (http://sandtray-hrilab:43209/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 555, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][INFO] 2017-06-23 11:30:19,370: topic[/tf] removing connection to http://sandtray-hrilab:43209/
[rospy.internal][WARNING] 2017-06-23 11:30:19,370: Unknown error initiating TCP/IP socket to sandtray-hrilab:44980 (http://sandtray-hrilab:42464/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rosgraph/network.py", line 362, in read_ros_handshake_header
    d = sock.recv(buff_size)
error: [Errno 104] Connection reset by peer

[rospy.internal][INFO] 2017-06-23 11:30:19,370: topic[/tf] removing connection to http://sandtray-hrilab:42464/
[rospy.core][INFO] 2017-06-23 11:30:59,280: signal_shutdown [signal-15]
[rospy.core][INFO] 2017-06-23 11:30:59,282: signal_shutdown [signal-2]
[rospy.internal][WARNING] 2017-06-23 11:30:59,283: Unknown error initiating TCP/IP socket to sandtray-hrilab:38594 (http://sandtray-hrilab:44591/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 555, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][INFO] 2017-06-23 11:30:59,283: topic[/tf] removing connection to http://sandtray-hrilab:44591/
[rospy.internal][INFO] 2017-06-23 11:30:59,289: topic[/poses] removing connection to /sandtray
[rospy.internal][INFO] 2017-06-23 11:30:59,289: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2017-06-23 11:30:59,289: topic[/tf] removing connection to http://sandtray-hrilab:43119/
[rospy.internal][INFO] 2017-06-23 11:30:59,290: topic[/tf] removing connection to http://sandtray-hrilab:33170/
[rospy.internal][INFO] 2017-06-23 11:30:59,290: topic[/tf] removing connection to http://sandtray-hrilab:43520/
[rospy.impl.masterslave][INFO] 2017-06-23 11:30:59,290: signal-15
[rospy.core][INFO] 2017-06-23 11:30:59,422: signal_shutdown [atexit]
