[rospy.client][INFO] 2017-07-05 10:24:38,546: init_node, name[/move_sandbox_items], pid[8198]
[xmlrpc][INFO] 2017-07-05 10:24:38,547: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2017-07-05 10:24:38,547: Started XML-RPC server [http://sandtray-hrilab:35097/]
[rospy.init][INFO] 2017-07-05 10:24:38,548: ROS Slave URI: [http://sandtray-hrilab:35097/]
[rospy.impl.masterslave][INFO] 2017-07-05 10:24:38,548: _ready: http://sandtray-hrilab:35097/
[rospy.registration][INFO] 2017-07-05 10:24:38,548: Registering with master node http://localhost:11311
[xmlrpc][INFO] 2017-07-05 10:24:38,549: xml rpc node: starting XML-RPC server
[rospy.init][INFO] 2017-07-05 10:24:38,648: registered with master
[rospy.rosout][INFO] 2017-07-05 10:24:38,648: initializing /rosout core topic
[rospy.rosout][INFO] 2017-07-05 10:24:38,650: connected to core topic /rosout
[rospy.simtime][INFO] 2017-07-05 10:24:38,651: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rospy.internal][INFO] 2017-07-05 10:24:38,665: topic[/tf] adding connection to [http://sandtray-hrilab:36952/], count 0
[rospy.internal][INFO] 2017-07-05 10:24:38,667: topic[/tf] adding connection to [http://sandtray-hrilab:45939/], count 1
[rospy.internal][INFO] 2017-07-05 10:24:38,667: topic[/tf] adding connection to [http://sandtray-hrilab:38304/], count 1
[rospy.internal][INFO] 2017-07-05 10:24:38,669: topic[/tf] adding connection to [http://sandtray-hrilab:36928/], count 2
[rospy.internal][INFO] 2017-07-05 10:24:38,670: topic[/tf] adding connection to [http://sandtray-hrilab:38002/], count 4
[rospy.internal][INFO] 2017-07-05 10:24:38,928: topic[/poses] adding connection to [/sandtray], count 0
[rospy.internal][INFO] 2017-07-05 10:24:38,930: topic[/rosout] adding connection to [/rosout], count 0
[rospy.internal][WARNING] 2017-07-05 10:26:25,579: Unknown error initiating TCP/IP socket to sandtray-hrilab:60004 (http://sandtray-hrilab:45939/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rosgraph/network.py", line 362, in read_ros_handshake_header
    d = sock.recv(buff_size)
error: [Errno 104] Connection reset by peer

[rospy.internal][INFO] 2017-07-05 10:26:25,579: topic[/tf] removing connection to http://sandtray-hrilab:45939/
[rospy.internal][INFO] 2017-07-05 10:27:52,329: topic[/tf] adding connection to [http://sandtray-hrilab:35596/], count 4
[rospy.internal][INFO] 2017-07-05 10:27:53,337: topic[/tf] adding connection to [http://sandtray-hrilab:43420/], count 5
[rospy.internal][WARNING] 2017-07-05 10:33:29,652: Unknown error initiating TCP/IP socket to sandtray-hrilab:47393 (http://sandtray-hrilab:43420/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 555, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][INFO] 2017-07-05 10:33:29,653: topic[/tf] removing connection to http://sandtray-hrilab:43420/
[rospy.internal][WARNING] 2017-07-05 10:33:29,653: Unknown error initiating TCP/IP socket to sandtray-hrilab:37077 (http://sandtray-hrilab:35596/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rosgraph/network.py", line 362, in read_ros_handshake_header
    d = sock.recv(buff_size)
error: [Errno 104] Connection reset by peer

[rospy.internal][INFO] 2017-07-05 10:33:29,654: topic[/tf] removing connection to http://sandtray-hrilab:35596/
[rospy.internal][INFO] 2017-07-05 10:33:37,534: topic[/tf] adding connection to [http://sandtray-hrilab:45887/], count 4
[rospy.internal][INFO] 2017-07-05 10:33:38,449: topic[/tf] adding connection to [http://sandtray-hrilab:45299/], count 5
[rospy.internal][WARNING] 2017-07-05 11:14:33,515: Unknown error initiating TCP/IP socket to sandtray-hrilab:52765 (http://sandtray-hrilab:45299/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 555, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][WARNING] 2017-07-05 11:14:33,516: Unknown error initiating TCP/IP socket to sandtray-hrilab:40572 (http://sandtray-hrilab:45887/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rosgraph/network.py", line 362, in read_ros_handshake_header
    d = sock.recv(buff_size)
error: [Errno 104] Connection reset by peer

[rospy.internal][INFO] 2017-07-05 11:14:33,516: topic[/tf] removing connection to http://sandtray-hrilab:45887/
[rospy.internal][INFO] 2017-07-05 11:14:33,516: topic[/tf] removing connection to http://sandtray-hrilab:45299/
[rospy.core][INFO] 2017-07-05 11:14:46,152: signal_shutdown [signal-15]
[rospy.internal][WARNING] 2017-07-05 11:14:46,153: Unknown error initiating TCP/IP socket to sandtray-hrilab:54118 (http://sandtray-hrilab:38304/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 555, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][INFO] 2017-07-05 11:14:46,153: topic[/tf] removing connection to http://sandtray-hrilab:38304/
[rospy.core][INFO] 2017-07-05 11:14:46,156: signal_shutdown [signal-2]
[rospy.internal][INFO] 2017-07-05 11:14:46,159: topic[/poses] removing connection to /sandtray
[rospy.internal][INFO] 2017-07-05 11:14:46,160: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2017-07-05 11:14:46,160: topic[/tf] removing connection to http://sandtray-hrilab:36952/
[rospy.internal][INFO] 2017-07-05 11:14:46,161: topic[/tf] removing connection to http://sandtray-hrilab:36928/
[rospy.internal][INFO] 2017-07-05 11:14:46,161: topic[/tf] removing connection to http://sandtray-hrilab:38002/
[rospy.impl.masterslave][INFO] 2017-07-05 11:14:46,161: signal-15
[rospy.core][INFO] 2017-07-05 11:14:46,293: signal_shutdown [atexit]
