[rospy.client][INFO] 2017-06-28 11:09:44,977: init_node, name[/move_sandbox_items], pid[14093]
[xmlrpc][INFO] 2017-06-28 11:09:44,977: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2017-06-28 11:09:44,977: Started XML-RPC server [http://sandtray-hrilab:44031/]
[rospy.init][INFO] 2017-06-28 11:09:44,977: ROS Slave URI: [http://sandtray-hrilab:44031/]
[rospy.impl.masterslave][INFO] 2017-06-28 11:09:44,978: _ready: http://sandtray-hrilab:44031/
[rospy.registration][INFO] 2017-06-28 11:09:44,978: Registering with master node http://localhost:11311
[xmlrpc][INFO] 2017-06-28 11:09:44,978: xml rpc node: starting XML-RPC server
[rospy.init][INFO] 2017-06-28 11:09:45,078: registered with master
[rospy.rosout][INFO] 2017-06-28 11:09:45,078: initializing /rosout core topic
[rospy.rosout][INFO] 2017-06-28 11:09:45,081: connected to core topic /rosout
[rospy.simtime][INFO] 2017-06-28 11:09:45,082: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rospy.internal][INFO] 2017-06-28 11:09:45,097: topic[/tf] adding connection to [http://sandtray-hrilab:34324/], count 0
[rospy.internal][INFO] 2017-06-28 11:09:45,099: topic[/tf] adding connection to [http://sandtray-hrilab:36461/], count 1
[rospy.internal][INFO] 2017-06-28 11:09:45,100: topic[/tf] adding connection to [http://sandtray-hrilab:40899/], count 1
[rospy.internal][INFO] 2017-06-28 11:09:45,102: topic[/tf] adding connection to [http://sandtray-hrilab:42880/], count 3
[rospy.internal][INFO] 2017-06-28 11:09:45,103: topic[/tf] adding connection to [http://sandtray-hrilab:43216/], count 3
[rospy.internal][INFO] 2017-06-28 11:09:45,223: topic[/poses] adding connection to [/sandtray], count 0
[rospy.internal][INFO] 2017-06-28 11:09:45,322: topic[/rosout] adding connection to [/rosout], count 0
[rospy.internal][WARNING] 2017-06-28 11:10:00,713: Unknown error initiating TCP/IP socket to sandtray-hrilab:47020 (http://sandtray-hrilab:36461/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rosgraph/network.py", line 362, in read_ros_handshake_header
    d = sock.recv(buff_size)
error: [Errno 104] Connection reset by peer

[rospy.internal][INFO] 2017-06-28 11:10:00,714: topic[/tf] removing connection to http://sandtray-hrilab:36461/
[rospy.internal][INFO] 2017-06-28 11:10:01,587: topic[/tf] adding connection to [http://sandtray-hrilab:36885/], count 4
[rospy.internal][INFO] 2017-06-28 11:10:02,589: topic[/tf] adding connection to [http://sandtray-hrilab:38027/], count 5
[rospy.internal][WARNING] 2017-06-28 11:16:08,016: Unknown error initiating TCP/IP socket to sandtray-hrilab:43275 (http://sandtray-hrilab:36885/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 555, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][INFO] 2017-06-28 11:16:08,016: topic[/tf] removing connection to http://sandtray-hrilab:36885/
[rospy.internal][WARNING] 2017-06-28 11:16:08,020: Unknown error initiating TCP/IP socket to sandtray-hrilab:34078 (http://sandtray-hrilab:38027/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 555, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][INFO] 2017-06-28 11:16:08,020: topic[/tf] removing connection to http://sandtray-hrilab:38027/
[rospy.internal][INFO] 2017-06-28 11:16:29,402: topic[/tf] adding connection to [http://sandtray-hrilab:35162/], count 4
[rospy.internal][INFO] 2017-06-28 11:16:30,403: topic[/tf] adding connection to [http://sandtray-hrilab:40104/], count 5
[rospy.internal][WARNING] 2017-06-28 11:49:25,119: Unknown error initiating TCP/IP socket to sandtray-hrilab:59643 (http://sandtray-hrilab:35162/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rosgraph/network.py", line 362, in read_ros_handshake_header
    d = sock.recv(buff_size)
error: [Errno 104] Connection reset by peer

[rospy.internal][INFO] 2017-06-28 11:49:25,119: topic[/tf] removing connection to http://sandtray-hrilab:35162/
[rospy.internal][WARNING] 2017-06-28 11:49:25,122: Unknown error initiating TCP/IP socket to sandtray-hrilab:38804 (http://sandtray-hrilab:40104/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 555, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][INFO] 2017-06-28 11:49:25,122: topic[/tf] removing connection to http://sandtray-hrilab:40104/
[rospy.core][INFO] 2017-06-28 11:49:27,516: signal_shutdown [signal-15]
[rospy.internal][WARNING] 2017-06-28 11:49:27,517: Unknown error initiating TCP/IP socket to sandtray-hrilab:42766 (http://sandtray-hrilab:42880/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 555, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][INFO] 2017-06-28 11:49:27,517: topic[/tf] removing connection to http://sandtray-hrilab:42880/
[rospy.internal][INFO] 2017-06-28 11:49:27,523: topic[/poses] removing connection to /sandtray
[rospy.internal][INFO] 2017-06-28 11:49:27,523: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2017-06-28 11:49:27,524: topic[/tf] removing connection to http://sandtray-hrilab:34324/
[rospy.internal][INFO] 2017-06-28 11:49:27,524: topic[/tf] removing connection to http://sandtray-hrilab:40899/
[rospy.internal][INFO] 2017-06-28 11:49:27,524: topic[/tf] removing connection to http://sandtray-hrilab:43216/
[rospy.impl.masterslave][INFO] 2017-06-28 11:49:27,524: signal-15
[rospy.core][INFO] 2017-06-28 11:49:27,649: signal_shutdown [signal-2]
[rospy.core][INFO] 2017-06-28 11:49:27,715: signal_shutdown [atexit]
