[rospy.client][INFO] 2017-06-29 10:55:25,600: init_node, name[/move_sandbox_items], pid[5268]
[xmlrpc][INFO] 2017-06-29 10:55:25,601: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2017-06-29 10:55:25,601: Started XML-RPC server [http://sandtray-hrilab:32916/]
[rospy.init][INFO] 2017-06-29 10:55:25,601: ROS Slave URI: [http://sandtray-hrilab:32916/]
[rospy.impl.masterslave][INFO] 2017-06-29 10:55:25,601: _ready: http://sandtray-hrilab:32916/
[rospy.registration][INFO] 2017-06-29 10:55:25,602: Registering with master node http://localhost:11311
[xmlrpc][INFO] 2017-06-29 10:55:25,602: xml rpc node: starting XML-RPC server
[rospy.init][INFO] 2017-06-29 10:55:25,702: registered with master
[rospy.rosout][INFO] 2017-06-29 10:55:25,702: initializing /rosout core topic
[rospy.rosout][INFO] 2017-06-29 10:55:25,705: connected to core topic /rosout
[rospy.simtime][INFO] 2017-06-29 10:55:25,706: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rospy.internal][INFO] 2017-06-29 10:55:25,721: topic[/tf] adding connection to [http://sandtray-hrilab:33749/], count 0
[rospy.internal][INFO] 2017-06-29 10:55:25,721: topic[/tf] adding connection to [http://sandtray-hrilab:40605/], count 0
[rospy.internal][INFO] 2017-06-29 10:55:25,722: topic[/tf] adding connection to [http://sandtray-hrilab:36644/], count 0
[rospy.internal][INFO] 2017-06-29 10:55:25,723: topic[/tf] adding connection to [http://sandtray-hrilab:34810/], count 0
[rospy.internal][INFO] 2017-06-29 10:55:25,725: topic[/tf] adding connection to [http://sandtray-hrilab:45109/], count 3
[rospy.internal][INFO] 2017-06-29 10:55:25,902: topic[/poses] adding connection to [/sandtray], count 0
[rospy.internal][INFO] 2017-06-29 10:55:26,001: topic[/rosout] adding connection to [/rosout], count 0
[rospy.internal][WARNING] 2017-06-29 10:56:55,071: Unknown error initiating TCP/IP socket to sandtray-hrilab:44073 (http://sandtray-hrilab:33749/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rosgraph/network.py", line 362, in read_ros_handshake_header
    d = sock.recv(buff_size)
error: [Errno 104] Connection reset by peer

[rospy.internal][INFO] 2017-06-29 10:56:55,071: topic[/tf] removing connection to http://sandtray-hrilab:33749/
[rospy.internal][INFO] 2017-06-29 10:58:27,077: topic[/tf] adding connection to [http://sandtray-hrilab:43279/], count 4
[rospy.internal][INFO] 2017-06-29 10:58:28,392: topic[/tf] adding connection to [http://sandtray-hrilab:34776/], count 5
[rospy.internal][WARNING] 2017-06-29 11:07:17,207: Unknown error initiating TCP/IP socket to sandtray-hrilab:35773 (http://sandtray-hrilab:34776/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 555, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 104] Connection reset by peer

[rospy.internal][INFO] 2017-06-29 11:07:17,207: topic[/tf] removing connection to http://sandtray-hrilab:34776/
[rospy.internal][WARNING] 2017-06-29 11:07:17,207: Unknown error initiating TCP/IP socket to sandtray-hrilab:60342 (http://sandtray-hrilab:43279/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rosgraph/network.py", line 362, in read_ros_handshake_header
    d = sock.recv(buff_size)
error: [Errno 104] Connection reset by peer

[rospy.internal][INFO] 2017-06-29 11:07:17,207: topic[/tf] removing connection to http://sandtray-hrilab:43279/
[rospy.internal][INFO] 2017-06-29 11:07:19,518: topic[/tf] adding connection to [http://sandtray-hrilab:34037/], count 4
[rospy.internal][INFO] 2017-06-29 11:07:20,520: topic[/tf] adding connection to [http://sandtray-hrilab:45010/], count 5
[rospy.internal][WARNING] 2017-06-29 11:46:14,868: Unknown error initiating TCP/IP socket to sandtray-hrilab:50181 (http://sandtray-hrilab:34037/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 555, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][INFO] 2017-06-29 11:46:14,868: topic[/tf] removing connection to http://sandtray-hrilab:34037/
[rospy.internal][WARNING] 2017-06-29 11:46:14,869: Unknown error initiating TCP/IP socket to sandtray-hrilab:38245 (http://sandtray-hrilab:45010/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 555, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][INFO] 2017-06-29 11:46:14,869: topic[/tf] removing connection to http://sandtray-hrilab:45010/
[rospy.core][INFO] 2017-06-29 11:51:02,829: signal_shutdown [signal-15]
[rospy.internal][WARNING] 2017-06-29 11:51:02,830: Unknown error initiating TCP/IP socket to sandtray-hrilab:42851 (http://sandtray-hrilab:40605/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 555, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][INFO] 2017-06-29 11:51:02,830: topic[/tf] removing connection to http://sandtray-hrilab:40605/
[rospy.internal][INFO] 2017-06-29 11:51:02,836: topic[/poses] removing connection to /sandtray
[rospy.internal][INFO] 2017-06-29 11:51:02,837: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2017-06-29 11:51:02,837: topic[/tf] removing connection to http://sandtray-hrilab:36644/
[rospy.internal][INFO] 2017-06-29 11:51:02,837: topic[/tf] removing connection to http://sandtray-hrilab:34810/
[rospy.internal][INFO] 2017-06-29 11:51:02,837: topic[/tf] removing connection to http://sandtray-hrilab:45109/
[rospy.impl.masterslave][INFO] 2017-06-29 11:51:02,837: signal-15
[rospy.core][INFO] 2017-06-29 11:51:02,944: signal_shutdown [signal-2]
[rospy.core][INFO] 2017-06-29 11:51:02,944: signal_shutdown [atexit]
